version: '3.8'
services:
  db:
    image: postgres:15
    container_name: sellhub_db
    restart: always
    environment:
      POSTGRES_USER: sellhub_user
      POSTGRES_PASSWORD: sellhub_pass
      POSTGRES_DB: sellhub_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
